{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    nginx.org/websocket-services: {{ include "jupyterhub.proxy-public.fullname" $ }}
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jupyterhub.proxy-public.fullname" $ }}
                port:
                  name: http
      host: {{ .Release.Name }}-{{ .Release.Namespace}}.dev.cloudquant.ai
    {{- end }}

  tls:
  - hosts:
    - {{ .Release.Name }}-{{ .Release.Namespace}}.dev.cloudquant.ai
    {{- if not .Values.ingress.useIngressWildcard }}
    secretName: {{ .Release.Name }}-{{ .Release.Namespace}}.dev.cloudquant.ai-tls
    {{- end }}
